# 网站基础信息
site_name: '初夏回响'
site_author: 'devuser'

# 【核心配置】告诉 MkDocs 你的文档目录在哪里
docs_dir: '01_documents' 

# 主题配置
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: 切换到夜间模式
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换到日间模式
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.suggest
    - content.image.lazy
    - navigation.drawer
    - navigation.expand

# 【导航配置】
nav:
  - '首页': 'README.md'
  - '世界观': 'WorldView.md'
  - '登场角色':
    - '角色索引': 'characters/characters.md'
    - '安柴': 'characters/AnChai/AnChai.md'
    - '纸灰灰': 'characters/PaperGracie/PaperGracie.md'
    - '琦霞': 'characters/QiXia/QiXia.md'
  - '日常故事':
    - '索引': 'daily_stories/README.md'
  - '番外故事': 
    - '索引': 'external_stories/README.md'
    - '漫步江南': 'external_stories/001_漫步江南/001_漫步江南.md'
  - '创作指南': 'guidelines/guidelines.md'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4

dev_addr: '0.0.0.0:55080'